---
title: "Mental Health Series"
author: "Ryan Larson"
date: "12/28/2022"
output: pdf_document
header-includes:
- \usepackage{dcolumn}
---

```{r setup, include=FALSE, message=F}
library(dplyr)
library(tidyr)
library(stringr)
library(readr)
library(lubridate)
library(ggplot2)
library(astsa)
library(tseries)
library(tidycensus)
library(sf)
library(purrr)
library(imputeTS)
library(rnoaa)
library(ISOweek)
library(ggmap)
library(ggrepel)
library(suncalc)
library(stargazer)
library(tidyquant)

google_key <- readRDS("C:/Users/rlarson21/Documents/R/Rworkingdirectory/google_api_key.rds")
register_google(key = google_key)
```

# Base Panel Construction - ZCTA-Week Level

## Hospital Data - ZCTA-Week level

```{r hosp data, message=FALSE}
hosp_zcta <- read_csv("Data/Restricted MHA Data/minnepop_1620_agg_zipfull_MH_102222.csv") %>%
  arrange(zipcode, year, weekofyr) %>%
  select(-c(`_chk`, zippop_tag)) %>%
  filter(!(year==2016 & weekofyr==53))
```

## ZCTAs and ACS 5-Year Estimates

```{r acs, message=FALSE, warning=FALSE}
#adding in 5-year ACS data 
census_api_key("ecda17575f4d914b502c70f2bae7a5f3d253792d")

year <- lst(2016, 2017, 2018, 2019, 2020)

acs <- map_dfr(
  year,
  ~ get_acs(geography = "zcta", 
               variables = c("B01001_001E", "B03003_003E",
                             "B02001_003E", "B02001_002E",
                             "B02001_004E", "B02001_008E",
                             "B02001_005E", "B02001_006E",
                             "B02001_007E", "B11001_003E",
                             "B17001_002E", "B01002_001E", 
                             "B09010_002E", "B06009_005E",
                             "B01001_002E", "B99233_005E"),
               output = "wide",
               survey = "acs5",
               year = .x),  .id = "year") %>%
  rename(total_pop = B01001_001E,
         white_pop = B02001_002E,
         black_pop = B02001_003E,
         na_pop = B02001_004E,
         asian_pop = B02001_005E,
         hpi_pop = B02001_006E,
         other_pop = B02001_007E,
         biracial_pop = B02001_008E,
         hisp_pop = B03003_003E,  
         ssi_snap = B09010_002E, #snap, ssi, public cash transfers
         med_age = B01002_001E,
         mar_fam = B11001_003E,
         povlevel = B17001_002E,
         bach_degree = B06009_005E,
         male = B01001_002E,
         nowork_12 = B99233_005E) %>%
  select(-ends_with("M", ignore.case = F), -GEOID) %>%
  mutate(zcta = str_sub(NAME, 6)) %>%
  select(-NAME) %>%
  select(zcta, everything()) %>%
  mutate(year = as.numeric(year),
         zcta = as.numeric(zcta))  

#joining to hospital data
hosp_panel <- hosp_zcta %>%
  left_join(acs, by = c("zipcode"="zcta", "year"))

#SF geometries - get all ZCTAs 
zcta <- get_acs(geography = "zcta",
                   variables = "B01001_001",
                   output = "wide", 
                   year = 2020,
                   geometry = T,
                   survey = "acs5") %>%
  rename(zcta = GEOID,
         pop_2019 = B01001_001E) %>%
  select(-c(NAME, B01001_001M, pop_2019)) %>%
  mutate(zcta = as.numeric(zcta))


#minneapolis shapefile (source: openminneapolis.gov)
mpls <- st_read("Data/mpls_city-shp/16cdbbfa-ad10-493c-afaf-52b61f2e76e42020329-1-180h9ap.whbo.shp") %>%
   st_set_crs(st_crs(zcta))

#zctas that intersect MPLS
zcta_intersect <- zcta %>%
 st_filter(mpls, .predicate = st_intersects) %>%
  mutate(zcta_area = as.numeric(st_area(.)),
         zcta_area_sqkm = zcta_area*.000001, 
         zcta_area_sqmi = zcta_area_sqkm*.386102,
         intersection_area = as.numeric(st_area(st_intersection(., mpls))),
         perc_intersection = round(intersection_area/zcta_area*100,2)) %>%
  filter(perc_intersection >= 5)

#filter hospital panel
panel <- hosp_panel %>%
  filter(zipcode %in% zcta_intersect$zcta) %>%
  mutate(zcta = zipcode)

#creating date bookends
panel <- panel %>%
  group_by(zipcode, year) %>%
  mutate(begin_date = ISOweek2date(paste(year, paste0("W", sprintf("%02d", weekofyr)), 1,sep = "-")),
         end_date = begin_date+weeks(1)-days(1))

#number of unique MPLS ZCTAs
n_zcta <- length(unique(panel$zcta))

#vector of intersecting ZCTAs for filtering downstream
zcta_universe <- unique(panel$zcta)

```

## ZCTA-Week Level Police Data

```{r, warning=F, message=FALSE}
#Minneapolis Police Department - Use of Force Dashboard
uof_spatial <- read_csv("Data/Police_Use_Of_Force.csv")  %>%
  mutate(date=ymd_hms(ResponseDate),
         year=isoyear(date),
         week=isoweek(date)) %>%
  select(OBJECTID, year, week, X, Y, Race) %>%
  st_as_sf(coords = c("X", "Y"), crs = "NAD83", remove=F) %>%
  mutate(intersection = as.integer(st_intersects(geometry, zcta)), 
         zcta = ifelse(is.na(intersection), NA, zcta$zcta[intersection])) %>%
  st_drop_geometry() %>%
  filter(!is.na(zcta) & year >= 2016 & year <= 2021 & zcta %in% zcta_universe) %>%
  group_by(year, week, zcta, Race, .drop=F) %>%
  tally(name = "use_of_force") %>%
  filter(!is.na(Race) & Race!="not recorded") %>%
  ungroup() %>%
  complete(year, week, zcta=zcta_universe, Race, fill = list(use_of_force = 0)) %>%
  arrange(year, week, zcta, Race) %>%
  mutate(race = str_to_lower(Race)) %>%
  select(-Race) %>%
  pivot_wider(names_from = race, 
              values_from = use_of_force,
              values_fill = 0,
              names_glue = "{race}_{.value}") %>%
  mutate(total_use_of_force = asian_use_of_force+black_use_of_force+`native american_use_of_force`+
           `other / mixed race_use_of_force`+`pacific islander_use_of_force`+unknown_use_of_force+           
            white_use_of_force)

#MPD Stop Dashboard
stop_spatial <- read_csv("Data/Police_Stop_Data.csv") %>%
  mutate(date=ymd_hms(responseDate),
         year=isoyear(date),
         week=isoweek(date)) %>%
  select(OBJECTID, year, week, lat, long, race) %>%
  st_as_sf(coords = c("long", "lat"), crs = "NAD83", remove=F) %>%
  mutate(intersection = as.integer(st_intersects(geometry, zcta)), 
         zcta = ifelse(is.na(intersection), NA, zcta$zcta[intersection])) %>%
  st_drop_geometry() %>%
  filter(!is.na(zcta) & year >= 2016 & year <= 2020 & zcta %in% zcta_universe) %>%
  group_by(year, week, zcta, race, .drop=F) %>%
  tally(name = "police_stops") %>%
   filter(!is.na(race) & race!="not recorded") %>%
  ungroup() %>%
  complete(year, week, zcta=zcta_universe, race, fill = list(police_stops = 0)) %>%
  mutate(race = str_to_lower(race)) %>%
  arrange(year, week, zcta, race) %>%
  pivot_wider(names_from = race, 
              values_from = police_stops,
              values_fill = 0,
              names_glue = "{race}_{.value}") %>%
  mutate(total_police_stops = asian_police_stops+black_police_stops+
         `east african_police_stops`+latino_police_stops+`native american_police_stops`+
           other_police_stops+unknown_police_stops+white_police_stops)

#Officer Involved Shootings - MPD
ois_spatial <- read_csv("Data/Police_Officer_Involved_Shootings.csv") %>%
  mutate(date=ymd_hms(IncidentDate),
         year=isoyear(date),
         week=isoweek(date)) %>%
  select(OBJECTID, year, week, CenterLatitude, CenterLongitude, SubjectOfForceRace) %>%
  rename(race = SubjectOfForceRace,
         lat = CenterLatitude,
         long = CenterLongitude) %>%
  st_as_sf(coords = c("long", "lat"), crs = "NAD83", remove=F) %>%
  mutate(intersection = as.integer(st_intersects(geometry, zcta)), 
         zcta = ifelse(is.na(intersection), NA, zcta$zcta[intersection])) %>%
  st_drop_geometry() %>%
  filter(!is.na(zcta) & year >= 2016 & year <= 2020 & zcta %in% zcta_universe) %>%
  group_by(year, week, zcta, race, .drop=F) %>%
  tally(name = "police_shootings") %>%
  filter(!is.na(race) & race!="not recorded") %>%
  ungroup() %>%
  complete(year=2016:2021, week=1:53, zcta=zcta_universe, race, fill = list(police_shootings = 0)) %>%
  mutate(race = str_to_lower(race)) %>%
  arrange(year, week, zcta, race) %>%
  pivot_wider(names_from = race, 
              values_from = police_shootings,
              values_fill = 0,
              names_glue = "{race}_{.value}") %>%
  mutate(total_police_shootings = asian_police_shootings+black_police_shootings+
         hispanic_police_shootings+other_police_shootings+
           unknown_police_shootings+white_police_shootings)

panel <- panel %>%
  left_join(uof_spatial, by = c("year", "weekofyr"="week", "zcta"="zcta")) %>%
  left_join(stop_spatial, by = c("year", "weekofyr"="week", "zcta"="zcta")) %>%
  left_join(ois_spatial, by = c("year", "weekofyr"="week", "zcta"="zcta")) 

#creating period indicators for panel
panel <- panel %>%
  mutate(post_floyd = as.numeric(begin_date >= as.Date("2020-05-25")),
         post_floyd_3 = as.numeric(begin_date >= as.Date("2020-05-25")+months(3)),
         t_post_floyd = ifelse(as.numeric(begin_date-as.Date("2020-05-25"))/7 >=0,
                               begin_date-as.numeric(as.Date("2020-05-25"))/7,
                               0),
         stay_at_home = as.numeric(begin_date >= as.Date("2020-03-28") &                                                                                     begin_date <= as.Date("2020-05-28")),
         state_of_emerg = as.numeric(begin_date >= as.Date("2020-03-13")),
         period = factor(case_when(
           post_floyd==0 & post_floyd_3==0 ~ "Pre-Killing",
           post_floyd>=1 & post_floyd_3==0 ~ "0-3 Months Post-Killing",
           post_floyd>=1 & post_floyd_3>=1 ~ "3+ Months Post-Killing"),
           levels = c("Pre-Killing", "0-3 Months Post-Killing", "3+ Months Post-Killing"))) %>%
  group_by(zcta) %>%
  arrange(year, weekofyr) %>%
  mutate(t = row_number(),
         uof_lag = dplyr::lag(total_use_of_force, 1),
         stops_lag = dplyr::lag(total_police_stops, 1),
         shoot_lag = dplyr::lag(total_police_shootings, 1))
```

# Weather Data

```{r, message=F}
# Minnesota DNR Daily Date
 # https://www.dnr.state.mn.us/climate/historical/daily-data.html?sid=mspthr&sname=Minneapolis/St%20Paul%20Threaded%20Record&sdate=2010-01-01&edate=por
 # Station Name: Minneapolis/St Paul Threaded Record - Station ID: mspthr

weather <- read_csv("Data/dnr_weather.csv") %>%
  mutate(year=isoyear(Date),
         week=isoweek(Date),
         precip_in = as.numeric(ifelse(`Precipitation (inches)`=="T", .001, `Precipitation (inches)`)),
         snow_in = as.numeric(ifelse(`Snow (inches)`=="T", .001, `Snow (inches)`)),
         tmax_f = `Maximum Temperature degrees (F)`) %>%
  filter(year >= 2016 & year <= 2020) %>%
  select(year, week, precip_in, snow_in, tmax_f) %>%
  group_by(year, week) %>%
  summarize(precip_in = mean(precip_in, na.rm = T), 
            snow_in = mean(snow_in, na.rm = T), 
            tmax_f = mean(tmax_f, na.rm = T))

#join to panel
panel <- panel %>% left_join(weather, by = c("year","weekofyr"="week"))
```


# Time Series Construction - Week Level

## Aggregate Hospital Panel to Week-Level

```{r aggregation, message=FALSE}
#panel to week-level, aggregating over ZCTAs
hosp_series <- panel %>%
  group_by(year, weekofyr) %>%
  summarize(mh_all_tot = sum(mh_all_tot, na.rm = T),
            white_mh_all_tot =  sum(white_mh_all_tot, na.rm = T),
            indig_mh_all_tot =  sum(indig_mh_all_tot, na.rm = T),
            asian_mh_all_tot =  sum(asian_mh_all_tot, na.rm = T),
            black_mh_all_tot =  sum(black_mh_all_tot, na.rm = T),
            latin_mh_all_tot =  sum(latin_mh_all_tot, na.rm = T),
            total_pop = sum(total_pop, na.rm = T),
            white_pop = sum(white_pop, na.rm = T),
            na_pop = sum(na_pop, na.rm = T),
            hisp_pop = sum(hisp_pop, na.rm = T),
            asian_pop = sum(asian_pop, na.rm = T),
            black_pop = sum(black_pop, na.rm = T)) %>%
  mutate(mh_incid_c = (mh_all_tot/total_pop)*1000,
         white_mh_incid_c = (white_mh_all_tot/white_pop)*1000,
         indig_mh_incid_c = (indig_mh_all_tot/na_pop)*1000,
         asian_mh_incid_c = (asian_mh_all_tot/asian_pop)*1000,
         black_mh_incid_c = (black_mh_all_tot/black_pop)*1000,
         latin_mh_incid_c = (latin_mh_all_tot/hisp_pop)*1000) %>%
  ungroup() %>%
  mutate(week_id = row_number()) 
```

## Police Data Week-Level

```{r police data, message = FALSE, warning=FALSE}
#Minneapolis Police Department - Use of Force Dashboard
uof <- read_csv("Data/Police_Use_Of_Force.csv") %>%
  mutate(date=ymd_hms(ResponseDate),
         year=isoyear(date),
         week=isoweek(date)) %>%
  group_by(year, week, .drop=F) %>%
  tally(name = "use_of_force") %>%
  arrange(year, week) %>%
  ungroup() %>%
  select(year, week, everything())

#merge onto series
series <- hosp_series %>%
  left_join(uof, by=c("year", "weekofyr"="week")) %>%
  mutate(use_of_force_rate = (use_of_force/total_pop)*1000)

#MPD Officer Involved Shootings
ois <- read_csv("Data/Police_Officer_Involved_Shootings.csv") %>%
  mutate(date=ymd_hms(IncidentDate),
         year=isoyear(date),
         week=isoweek(date)) %>%
  group_by(year, week, .drop=F) %>%
  tally(name = "off_inv_shooting") %>%
  arrange(year, week) %>%
  ungroup() %>%
  select(year, week, everything())

#merge onto series
series <- series %>%
  left_join(ois, by=c("year", "weekofyr"="week")) %>%
  mutate(off_inv_shooting = ifelse(is.na(off_inv_shooting), 0, off_inv_shooting),
         off_inv_shooting_rate = (off_inv_shooting/total_pop)*1000)


#Minneapolis Police Department - Police Stops Dashboard
stop <- read_csv("Data/Police_Stop_Data.csv") %>%
  mutate(date=ymd_hms(responseDate),
         year=isoyear(date),
         week=isoweek(date)) %>%
  group_by(year, week, .drop=F) %>%
  tally(name = "police_stops") 

#merge onto series
series <- series %>% 
  left_join(stop, by = c("year", "weekofyr"="week")) %>%
  mutate(police_stop_rate = (police_stops/total_pop)*1000)


#creating date variable
#removing week 53 of 2020

series <- series %>%
  mutate(begin_date = ISOweek2date(paste(year, paste0("W", sprintf("%02d", weekofyr)), 1,sep = "-")),
         end_date = begin_date+weeks(1)-days(1)) %>%
  filter(!(year==2020 & weekofyr== 53)) %>%
  left_join(weather, by = c("year","weekofyr"="week"))
```


## Time Series Vizualization

```{r firearm assaults plot, warning=FALSE}
ggplot(series)+
  scale_x_date(date_labels = "%b-%Y", date_breaks = "6 months")+
  geom_rect(aes(
    xmin = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-03-13"))],
    xmax = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-12-25"))],
    ymin = 0,
    ymax = 3,
    fill = "State of Emergency"
  )) +
  geom_rect(aes(
    xmin = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-03-28"))],
    xmax = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-05-18"))],
    ymin = 0,
    ymax = 3,
    fill = "Stay at Home"
  )) +
  scale_fill_manual(values=c("grey","red"), labels=c("Stay at Home", "State of Emergency")) +
  geom_line(aes(x=begin_date, y=mh_incid_c))+ 
  geom_vline(xintercept=series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-05-25"))], 
              linetype="solid", color="blue", size=1) +
  geom_label(aes(x=series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-05-25"))],
                 y=3.1), 
             label = "George Floyd", show.legend = FALSE)+
  labs(title = "Figure 1: Weekly Mental Health Discharges, 2016-2020",
       subtitle = "MHA Hospital Data",
       x = "Week",
       y = "Rate per 1,000 Residents",
       fill = "MN COVID-19 Policy")+
  theme_minimal()+
    theme(axis.text.x=element_text(angle=45, hjust=1)) 
```
```{r white firearm assaults plot, warning=FALSE}
ggplot(series)+
  scale_x_date(date_labels = "%b-%Y", date_breaks = "6 months")+
   geom_rect(aes(
    xmin = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-03-13"))],
    xmax = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-12-25"))],
    ymin = 0,
    ymax = 1,
    fill = "State of Emergency"
  )) +
  geom_rect(aes(
    xmin = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-03-28"))],
    xmax = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-05-18"))],
    ymin = 0,
    ymax = 1,
    fill = "Stay at Home"
  )) +
  scale_fill_manual(values=c("grey","red"), labels=c("Stay at Home", "State of Emergency")) +
  geom_line(aes(x=begin_date, y=white_mh_incid_c))+ 
  geom_vline(xintercept=series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-05-25"))], 
              linetype="solid", color="blue", size=1) +
  geom_label(aes(x=series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-05-25"))],
                 y=1), 
             label = "George Floyd", show.legend = FALSE)+
  labs(title = "Figure 1: Weekly White Mental Health Discharges, 2016-2020",
       subtitle = "MHA Hospital Data",
       x = "Week",
       y = "Rate per 1,000 White Residents",
       fill = "MN COVID-19 Policy")+
  theme_minimal()+
    theme(axis.text.x=element_text(angle=45, hjust=1)) 
```

```{r black firearm assaults plot, warning=FALSE}
ggplot(series)+
  scale_x_date(date_labels = "%b-%Y", date_breaks = "6 months")+
   geom_rect(aes(
    xmin = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-03-13"))],
    xmax = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-12-25"))],
    ymin = 0,
    ymax = 1.7,
    fill = "State of Emergency"
  )) +
  geom_rect(aes(
    xmin = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-03-28"))],
    xmax = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-05-18"))],
    ymin = 0,
    ymax = 1.7,
    fill = "Stay at Home"
  )) +
  scale_fill_manual(values=c("grey","red"), labels=c("Stay at Home", "State of Emergency")) +
  geom_line(aes(x=begin_date, y=black_mh_incid_c))+ 
  geom_vline(xintercept=series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-05-25"))], 
              linetype="solid", color="blue", size=1) +
  geom_label(aes(x=series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-05-25"))],
                 y=1.7), 
             label = "George Floyd", show.legend = FALSE)+
  labs(title = "Figure X: Weekly Black Mental Health Discharges, 2016-2020",
       subtitle = "MHA Hospital Data",
       x = "Week",
       y = "Rate per 1,000 Black Residents",
       fill = "MN COVID-19 Policy")+
  theme_minimal()+
    theme(axis.text.x=element_text(angle=45, hjust=1)) 
```

```{r latinx firearm assaults plot, warning=FALSE}
ggplot(series)+
  scale_x_date(date_labels = "%b-%Y", date_breaks = "6 months")+
   geom_rect(aes(
    xmin = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-03-13"))],
    xmax = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-12-25"))],
    ymin = 0,
    ymax = 1.25,
    fill = "State of Emergency"
  )) +
  geom_rect(aes(
    xmin = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-03-28"))],
    xmax = series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-05-18"))],
    ymin = 0,
    ymax = 1.25,
    fill = "Stay at Home"
  )) +
  scale_fill_manual(values=c("grey","red"), labels=c("Stay at Home", "State of Emergency")) +
  geom_line(aes(x=begin_date, y=latin_mh_incid_c))+ 
  geom_vline(xintercept=series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-05-25"))], 
              linetype="solid", color="blue", size=1) +
  geom_label(aes(x=series$begin_date[series$year==2020 & series$weekofyr==isoweek(date("2020-05-25"))],
                 y=1.25), 
             label = "George Floyd", show.legend = FALSE)+
  labs(title = "Figure X: Weekly Latino/a Mental Health Discharges, 2016-2020",
       subtitle = "MHA Hospital Data",
       x = "Week",
       y = "Rate per 1,000 Latino/a Residents",
       fill = "MN COVID-19 Policy")+
  theme_minimal()+
    theme(axis.text.x=element_text(angle=45, hjust=1)) 
```

## Time Series Analysis

```{r time series models, message=F}
series <- series %>%
  mutate(t = 1:length(mh_incid_c),
         post_floyd = as.factor(as.numeric(begin_date >= as.Date("2020-05-25"))),
         post_floyd_3 = as.factor(as.numeric(begin_date >= as.Date("2020-05-25")+months(3))),
         stay_at_home = as.factor(as.numeric(begin_date >= as.Date("2020-03-28") &                                                                                     begin_date <= as.Date("2020-05-28"))),
         state_of_emerg = as.factor(as.numeric(begin_date >= as.Date("2020-03-13"))),
          t_post_floyd = ifelse(as.numeric(as.Date("2020-05-25")-begin_date)/7 >=0,
                               as.numeric(as.Date("2020-05-25")-begin_date)/7,
                               0),
         uof_lag=lag(use_of_force_rate,1),
         stops_lag = lag(police_stop_rate,1),
         shoot_lag = lag(off_inv_shooting_rate,1)) #check t_post_floyd
  
ts <- lm(mh_incid_c~t+state_of_emerg+stay_at_home+post_floyd+t_post_floyd+
           tmax_f+snow_in+precip_in+
           uof_lag+stops_lag+shoot_lag, 
                         data = series) 
summary(ts)

acf2(resid(ts), max.lag = 7)

ts_ar3<- lm(mh_incid_c~t+state_of_emerg+stay_at_home+post_floyd+t_post_floyd+
                          uof_lag+stops_lag+shoot_lag+
                         tmax_f+snow_in+precip_in+
                         dplyr::lag(mh_incid_c, 1)+ dplyr::lag(mh_incid_c, 2)+
               dplyr::lag(mh_incid_c, 3), 
            data = series)
summary(ts_ar3)

acf2(resid(ts_ar3), max.lag = 7)

#race specific models

ts_ar3_white <- lm(white_mh_incid_c~t+state_of_emerg+stay_at_home+post_floyd+t_post_floyd+
                          uof_lag+stops_lag+shoot_lag+
                         tmax_f+snow_in+precip_in+
                         dplyr::lag(white_mh_incid_c, 1)+ dplyr::lag(white_mh_incid_c, 2)+
               dplyr::lag(white_mh_incid_c, 3), 
            data = series)
summary(ts_ar3_white)

ts_ar3_black <- lm(black_mh_incid_c~t+state_of_emerg+stay_at_home+post_floyd+t_post_floyd+
                          uof_lag+stops_lag+shoot_lag+
                         tmax_f+snow_in+precip_in+
                         dplyr::lag(black_mh_incid_c, 1)+ dplyr::lag(black_mh_incid_c, 2)+
               dplyr::lag(black_mh_incid_c, 3), 
            data = series)
summary(ts_ar3_black)

ts_ar3_latin <- lm(latin_mh_incid_c~t+state_of_emerg+stay_at_home+post_floyd+t_post_floyd+
                          uof_lag+stops_lag+shoot_lag+
                         tmax_f+snow_in+precip_in+
                         dplyr::lag(latin_mh_incid_c, 1)+ dplyr::lag(latin_mh_incid_c, 2)+
               dplyr::lag(latin_mh_incid_c, 3), 
            data = series)
summary(ts_ar3_latin)

ts_ar3_indig <- lm(indig_mh_incid_c~t+state_of_emerg+stay_at_home+post_floyd+t_post_floyd+
                          uof_lag+stops_lag+shoot_lag+
                         tmax_f+snow_in+precip_in+
                         dplyr::lag(indig_mh_incid_c, 1)+ dplyr::lag(indig_mh_incid_c, 2)+
               dplyr::lag(indig_mh_incid_c, 3), 
            data = series)
summary(ts_ar3_indig)

ts_ar3_asian <- lm(asian_mh_incid_c~t+state_of_emerg+stay_at_home+post_floyd+t_post_floyd+
                          uof_lag+stops_lag+shoot_lag+
                         tmax_f+snow_in+precip_in+
                         dplyr::lag(asian_mh_incid_c, 1)+ dplyr::lag(asian_mh_incid_c, 2)+
               dplyr::lag(asian_mh_incid_c, 3), 
            data = series)
summary(ts_ar3_asian)
```

```{r, results='asis', message=FALSE, include = T}
stargazer(ts_ar3, ts_ar3_white, ts_ar3_black, ts_ar3_latin,
          title = "Interrupted Time Series Models of Mental Health Discharges",
          covariate.labels = c("T","COVID - State of Emergency", "COVID - Stay at Home",
                               "Post-Killing", "T Post-Killing",  
                               "MPD Use of Force t-1", "MPD Stops t-1",
                               "MPD Officer Involved Shootings t-1",
                               "Mean Max. Temp.", "Snow (in.)", "Precip. (in.)",
                               "AR(1)", "AR(2)", "AR(3)"),
          dep.var.caption = "Mental Health Discharges",
          dep.var.labels = "Rate per 1,000",
          column.labels = c("Overall", "White", "Black", "Latino/a"),
          model.numbers = TRUE,
          single.row = TRUE,
          align = T,
          omit.stat = "adj.rsq",
          star.cutoffs = c(.05, .01, .001), star.char = c("*","**","***"))


#coefficient plot for SER abstract


```

# ZCTA-Week Level Analysis

## Panel Analysis

```{r panel analysis, message=F, echo=FALSE}

panel <- panel %>%
  ungroup() %>%
  mutate(black_pop_center = scale(black_pop, center = T, scale = T),
         post_floyd = as.factor(post_floyd),
         mh_rate = mh_all_tot/total_pop*1000)

fe_model <- lm(mh_rate~t+state_of_emerg+stay_at_home+post_floyd+t_post_floyd+
                          uof_lag+stops_lag+shoot_lag+
                         tmax_f+snow_in+precip_in+
                         as.factor(zipcode)+as.factor(weekofyr),
               data = panel)
summary(fe_model)



#random effects specifications
library(lme4)
library(lmerTest)


#RE base model
re_base <- lmer(mh_rate~1+
                 (1|zcta), data = panel)
summary(re_base)

re <- lmer(mh_rate~t+state_of_emerg+stay_at_home+post_floyd+t_post_floyd+
                          uof_lag+stops_lag+shoot_lag+
                         tmax_f+snow_in+precip_in+
                       (1+post_floyd|zcta), data = panel)
summary(re)

re_pf <- ranef(re)
re_coef <- re_pf$zcta 
re_coef <- re_coef %>%
  mutate(zipcode = as.numeric(rownames(re_coef)))

#aggregate to zip-level over years
zip_level <- panel %>%
  group_by(zcta) %>%
   summarize(mh_all_tot = sum(mh_all_tot, na.rm = T),
            total_pop = sum(total_pop, na.rm = T)) %>%
  mutate(mh_incid_c = (mh_all_tot/total_pop)*1000) %>%
  ungroup() %>%
  left_join(zcta, by = "zcta")

zip_level <- zip_level %>%
  left_join(re_coef, by = c("zcta" = "zipcode"))


#george floyd square
gfs <- geocode("George Floyd Square, Minneapolis", output = "latlon") %>%
  st_as_sf(coords = c("lon", "lat"), crs = "NAD83", remove=F) %>%
  mutate(name = "George Floyd Square")

ggplot() +
  geom_sf(data = zip_level, aes(geometry = geometry, fill = desc(post_floyd1))) + 
  geom_sf(data = mpls, aes(geometry = geometry), color = "black", alpha = 0)+
  geom_sf(data = gfs, aes(geometry = geometry), color = "black")+
  geom_text_repel(data = gfs, aes(x=lon, y=lat, label = name),
                 size = 2,
                fontface = "bold")+
  scale_fill_distiller(palette = "Spectral")+
  labs(title = "Figure X: RE Coefficients of Post-Killing Effect", 
       subtitle = "MHA Hospital Discharge Data",
       fill = "Post-Killing Increase")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_blank(),
  panel.grid.major = element_line(colour="transparent"), 
  plot.subtitle = element_text(face="italic"),
  strip.background = element_rect(fill = "white", 
                colour = "black"))





#random coefficient model
re <- lmer(mh_rate~t+state_of_emerg+stay_at_home+post_floyd+t_post_floyd+
                          uof_lag+stops_lag+shoot_lag+
                         tmax_f+snow_in+precip_in+
                black_pop+
                post_floyd:black_pop+
                       (1+post_floyd|zcta), data = panel)
summary(re)

library(sjPlot)

plot_model(re, type = "re")



plot_model(re, 
           terms = c("post_floyd", "black_pop"),
           type = "pred", 
           ci.lvl = 0.95,
           mdrt.values = "meansd",
           title = "Figure X: Post-Killing X Black Pop Interaction Plot",
           axis.title = c("Post-Killing","MH Discharges per 1,000"))+
  theme_sjplot()+
  ggplot2::labs(colour = "Black Pop")
```


