---
title: "Car Jacking MPLS"
author: "Ryan Larson"
date: "4/8/2022"
output: pdf_document
---



```{r setup, include=FALSE, message=F}
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(tidycensus)
library(sf)
library(purrr)
library(ggmap)
library(stargazer)
library(stringr)
library(lubridate)
library(ISOweek)

#TO DO!

#time-varying indicators of pandemic, school closures, institution closures, social safety net
#analysis of discrepancies between incidents and charges



google_key <- readRDS("C:/Users/DELL/Documents/R/Rworkingdirectory/google_api_key.rds")
register_google(key = google_key)
```

# Spatial Data

```{r, message=FALSE, warning=FALSE}
#MPLS neighborhoods
mpls_neighb <- st_read("Car Jacking/Minneapolis_Neighborhoods") %>%
  st_transform(crs = st_crs("NAD83")) #DONT HAVE POP DENOM YET

#Minneapolis Shapefile
mpls <- st_read("Data/mpls_city-shp/16cdbbfa-ad10-493c-afaf-52b61f2e76e42020329-1-180h9ap.whbo.shp") %>%
   st_transform(st_crs(mpls_neighb))
```

# Open Minneapolis Carjacking Data

```{r, message=FALSE}
#open minneapolis crime data 2019-4/7 (date of download)
cj_spatial <- read_csv("Car Jacking/crime_data.csv")  %>%
  filter(Offense=="Carjacking - Subset of Robbery") %>% #filter carjackings
  mutate(date=ymd_hms(Occurred_Date),
         year=isoyear(date),
         week=isoweek(date)) %>%
  select(OBJECTID, year, week, Latitude, Longitude) %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = "NAD83", remove=F) %>%
  st_join(mpls_neighb) %>% #spatial join neighborhoods
  st_drop_geometry() %>%
  filter(!is.na(BDNAME)) %>%
  group_by(year, week, BDNAME, .drop=F) %>%
  tally(name = "car_jack") %>%
  ungroup() %>%
  complete(year, week, BDNAME=mpls_neighb$BDNAME, fill = list(car_jack = 0)) %>%
  filter(!(year==2022 & week >= 14) & #removing unobserved/redundant completions
           !(year==2021 & week==53) & #removing unobserved/redundant completions
           !(year==2020 & week < 36)) %>% #removing weeks before Sept. 2020, isoweek 36
  arrange(BDNAME, year, week) %>%
  left_join(mpls_neighb, by = "BDNAME") %>%
  #mutate(car_jack_rate = car_jack/B01001_001E*1000) %>%
  st_as_sf()
```

# MPLS Carjackings by Week

```{r}
#aggregate to week over neighborhoods
cj_week <- cj_spatial %>%
  group_by(year, week) %>%
  summarize(car_jack = sum(car_jack, na.rm = T)) %>%
  mutate(begin_date = ISOweek2date(paste(year, paste0("W", sprintf("%02d", week)), 1,sep = "-")),
         end_date = begin_date+weeks(1)-days(1)) 
  
ggplot(cj_week)+
  geom_line(aes(x=begin_date, y=car_jack))+ 
  scale_x_date(date_labels = "%b-%Y", 
               limits = c(min(cj_week$begin_date), max(cj_week$begin_date)))+
  labs(title = "Figure X: Weekly Minneapolis Carjackings, 8/31/2020-4/7/2022",
       subtitle = "openminneapolis Crime Data",
       x = "Week",
       y = "Weekly Rate")+
  theme_minimal()+
    theme(axis.text.x=element_text(angle=45, hjust=1)) 

```


# MPLS ZCTA Carjackings Map

```{r}
#aggregate to neighborhood-year level
cj_nb_year <- cj_spatial %>%
  group_by(BDNAME, year) %>%
  summarize(car_jack = sum(car_jack, na.rm = T),
            weeks = n(),
            car_jack_rate = car_jack/weeks) 


ggplot() +
  geom_sf(data = cj_nb_year, aes(geometry = geometry, fill = car_jack_rate)) + 
  geom_sf(data = mpls, aes(geometry = geometry), color = "black", alpha = 0)+
  facet_wrap(~year)+
  scale_fill_distiller(palette = "Spectral")+
  labs(title = "Figure X: Minneapolis Carjacking Rates by Year", 
       subtitle = "openminneapolis Crime Data",
       fill = "Weekly Rate")+
  theme_void()
```